[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/cloudflare/brotli-go"
    unused-packages = false

[[constraint]]
  name = "github.com/getsentry/raven-go"
  revision = "ed7bcb39ff10f39ab08e317ce16df282845852fa"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "=0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "=0.9.0-pre1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=1.4.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.1"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"  # master required by github.com/miekg/dns

[[constraint]]
  name = "golang.org/x/sync"
  revision = "1d60e4601c6fd243af51cc01ddf169918a5407ca"

[[constraint]]
  name = "zombiezen.com/go/capnproto2"
  source = "https://github.com/zombiezen/go-capnproto2"
  version = "=2.17.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/cloudflare/brotli-go"
  revision = "18c9f6c67e3dfc12e0ddaca748d2887f97a7ac28"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"  # master required by github.com/miekg/dns

[[constraint]]
  name = "github.com/google/uuid"
  version = "=1.1.1"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/cloudflare/backoff"
