name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Prepare
        env:
          GOPATH: ${{runner.workspace}}
          GO111MODULE: 'off'
        run: |
          go get github.com/BurntSushi/go-sumtype
          ls $HOME/go
          ls $HOME/go/src
          ls $HOME/go/bin
          echo "::set_env name=GOPATH::$GOPATH"
          echo "::add_path::$GOPATH/bin"
      - name: Checkout
        uses: actions/checkout@v1
      #- name: Test
      #  run: |
      #    printenv
      #    make test
      #  env:
      #    GO111MODULE: 'on'
      #    CGO_ENABLED: '0'
