name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Fix GOPATH # https://github.com/actions/setup-go/issues/14
        shell: bash
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      - name: Install go-sumtype
        run: go get github.com/BurntSushi/go-sumtype
        env:
          GO111MODULE: 'off'
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Run Tests
        run: make test
        env:
          GO111MODULE: 'on'
          CGO_ENABLED: '1'
