name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prepare
        run: go get github.com/BurntSushi/go-sumtype
      - name: Build
        run: make test
