name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Prepare
        run: go get github.com/BurntSushi/go-sumtype
        env:
          GO111MODULE: 'off'
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test Unix
        if: matrix.os != 'windows-latest'
        run: |
          export PATH=$PATH:$HOME/go/bin
          make test
        env:
          GO111MODULE: 'on'
          CGO_ENABLED: '1'
      - name: Test Windows
        if: matrix.os == 'windows-latest'
        run: |
          set PATH=%PATH%;C:${HOME}\go\bin\
          make test
        env:
          GO111MODULE: 'on'
          CGO_ENABLED: '1'
